import { afterEach, beforeEach, describe, expect, it, vi } from 'vitest'
import { createTestDatabase, type TestDatabase } from './testSupport/nodeSqlite'
import { migrateDelegations } from './migrations/delegations'
import { delegationOriginKey } from '../../shared/delegations'
const holder = vi.hoisted(() => ({ current: null as TestDatabase | null }))
vi.mock('./client', () => ({ getDb: () => holder.current!.db, getRawSqlite: () => holder.current!.sqlite }))
const { delegationRepo } = await import('./delegations')
const { handoverRepo } = await import('./handovers')
const { taskRepo } = await import('./tasks')
const { chatRepo } = await import('./chats')
const USER = '__default__'
beforeEach(() => { holder.current = createTestDatabase() })
afterEach(() => { holder.current?.close() })
const make = (key = 'request') => delegationRepo.insert({ userId: USER, requesterKey: key, originKind: 'local_chat', originChatId: 'chat', originAgentId: 'source', targetKind: 'kit', targetAgentId: 'kit', channel: 'local', depth: 1 })
describe('delegation repository', () => {
  it('enforces requester identity per origin and target and profile-scopes reads', () => {
    const row = make()
    expect(() => make()).toThrow()
    expect(delegationRepo.byRequesterKey(USER, delegationOriginKey(row), 'kit', 'kit', 'request')?.id).toBe(row.id)
    expect(delegationRepo.getById('another-profile', row.id)).toBeUndefined()
    expect(delegationRepo.update('another-profile', row.id, { state: 'done' })).toBeUndefined()
    expect(delegationRepo.listForOrigin(USER, 'chat')).toHaveLength(1)
  })
  it('rolls back requester reservation when task creation fails', () => {
    expect(() => delegationRepo.createWithTask({ userId: USER, requesterKey: 'failed', originKind: 'external', targetKind: 'kit', targetAgentId: 'kit', channel: 'local', depth: 1 }, () => { throw new Error('task failed') })).toThrow('task failed')
    expect(delegationRepo.list(USER)).toHaveLength(0)
  })
  it('removes navigation to deleted work while retaining its task identity and requester key', () => {
    const task = taskRepo.create(USER, { title: 'Finished work', goal: 'Work' })
    const row = make()
    delegationRepo.update(USER, row.id, { taskId: task.id, state: 'done' })
    expect(delegationRepo.toDto(delegationRepo.getById(USER, row.id)!).taskId).toBe(task.id)
    taskRepo.softDelete(USER, task.id)
    expect(delegationRepo.toDto(delegationRepo.getById(USER, row.id)!)).toMatchObject({ taskId: null, state: 'done' })
    expect(delegationRepo.getById(USER, row.id)?.taskId).toBe(task.id)
    expect(() => make()).toThrow()
  })
  it('keeps matching cloud assignee ids in different adapters distinct', () => {
    const input = { userId: USER, requesterKey: 'same', originKind: 'external' as const, targetKind: 'cloud' as const, targetAgentId: 'agent-1', channel: 'cloud' as const, depth: 1 }
    const first = delegationRepo.insert({ ...input, remoteConnectionId: 'server-a' })
    const second = delegationRepo.insert({ ...input, remoteConnectionId: 'server-b' })
    expect(delegationRepo.byRequesterKey(USER, first.originKey, 'cloud', 'agent-1', 'same', 'server-a')?.id).toBe(first.id)
    expect(delegationRepo.byRequesterKey(USER, first.originKey, 'cloud', 'agent-1', 'same', 'server-b')?.id).toBe(second.id)
    expect(() => delegationRepo.insert({ ...input, remoteConnectionId: 'server-a' })).toThrow()
  })
  it('keeps a file handover in its writer’s chain when the brief names only the origin chat', () => {
    const chat = chatRepo.create(USER, { title: 'Executor', router: 'direct', agentId: null })
    const task = taskRepo.create(USER, { title: 'Outside work', goal: 'Work', chatId: chat.id })
    const outside = delegationRepo.insert({ userId: USER, requesterKey: 'outside', originKind: 'external', targetKind: 'bare', targetAgentId: 'bare', channel: 'file', depth: 1 })
    delegationRepo.update(USER, outside.id, { taskId: task.id })
    const next = handoverRepo.insert({ userId: USER, agentId: 'other', folderPath: '/other', handoverId: '20260919-next', taskId: null, depth: 2, execution: 'ask', state: 'seen', briefDigest: 'brief', originChatId: chat.id, originAgentId: 'bare' })
    expect(delegationRepo.getById(USER, next.id)?.rootDelegationId).toBe(outside.id)
    expect(delegationRepo.parentOfOrigin(USER, { chatId: 'unknown-chat' })).toBeUndefined()
  })
  it('marks a cloud create as unbound only until its remote identity is stored', () => {
    const task = taskRepo.create(USER, { title: 'Cloud work', goal: 'Work' })
    const row = delegationRepo.insert({ userId: USER, requesterKey: 'cloud', originKind: 'external', targetKind: 'cloud', targetAgentId: 'agent-1', channel: 'cloud', depth: 1, remoteConnectionId: 'cinna' })
    delegationRepo.update(USER, row.id, { taskId: task.id, dispatchState: 'creating' })
    expect(delegationRepo.unboundCreatePending(USER, 'cinna')).toBe(true)
    expect(delegationRepo.unboundCreatePending(USER, 'other')).toBe(false)
    expect(delegationRepo.unboundCreatePending('another-profile', 'cinna')).toBe(false)
    delegationRepo.update(USER, row.id, { remoteTaskId: 'remote-1', dispatchState: 'created' })
    expect(delegationRepo.unboundCreatePending(USER, 'cinna')).toBe(false)
    delegationRepo.update(USER, row.id, { remoteTaskId: null, dispatchState: 'creating' })
    taskRepo.softDelete(USER, task.id)
    expect(delegationRepo.unboundCreatePending(USER, 'cinna')).toBe(false)
  })
  it('preserves journal, result and wake fields across reads', () => {
    const row = make()
    delegationRepo.update(USER, row.id, { state: 'uncertain', dispatchState: 'uncertain', remoteConnectionId: 'cinna', dispatchError: 'connection lost', resultStatus: 'blocked', questionAudience: 'user', artifacts: ['https://example.com/a'] })
    const reread = delegationRepo.getById(USER, row.id)!
    expect(reread).toMatchObject({ dispatchState: 'uncertain', remoteConnectionId: 'cinna', dispatchError: 'connection lost', artifacts: ['https://example.com/a'] })
    expect(delegationRepo.toDto(reread)).toMatchObject({ state: 'skipped', waitingOnUser: false })
  })
  it('creates one file delegation and keeps reconciliation state in the file row', () => {
    const file = handoverRepo.insert({ userId: USER, agentId: 'bare', folderPath: '/repo', handoverId: '20260919-work', taskId: null, depth: 2, execution: 'ask', state: 'seen', briefDigest: 'bytes' })
    expect(delegationRepo.getById(USER, file.id)).toMatchObject({ handoverId: file.id, channel: 'file', requesterKey: '20260919-work', depth: 2 })
    handoverRepo.update(USER, file.id, { state: 'done', reportStatus: 'done', summary: 'Finished' })
    expect(delegationRepo.getById(USER, file.id)).toMatchObject({ state: 'done', resultStatus: 'done', summary: 'Finished' })
  })
  it('does not rewrite an established chain root on migration replay', () => {
    const file = handoverRepo.insert({ userId: USER, agentId: 'bare', folderPath: '/repo', handoverId: '20260919-root', taskId: null, depth: 2, execution: 'ask', state: 'seen', briefDigest: 'bytes' })
    delegationRepo.update(USER, file.id, { rootDelegationId: 'original-root' })
    migrateDelegations(holder.current!.sqlite)
    expect(delegationRepo.getById(USER, file.id)?.rootDelegationId).toBe('original-root')
  })
  it('acknowledges only the result version actually delivered, including a skipped state', () => {
    const row = make()
    delegationRepo.update(USER, row.id, { resultDigest: 'result-a', state: 'blocked' })
    delegationRepo.update(USER, row.id, { resultDigest: 'result-b', state: 'done', wokeAt: null })
    expect(delegationRepo.recordWake(USER, row.id, 'result-a', { wokeAt: new Date(), wakeRunId: 'old-wake' })).toBeUndefined()
    expect(delegationRepo.getById(USER, row.id)?.wokeAt).toBeNull()
    expect(delegationRepo.recordWake(USER, row.id, 'result-b', { wokeAt: new Date(), wakeRunId: 'new-wake' })?.wakeRunId).toBe('new-wake')
    delegationRepo.update(USER, row.id, { resultDigest: null, state: 'skipped', wokeAt: null })
    expect(delegationRepo.recordWake(USER, row.id, 'state:skipped', { wokeAt: new Date() })?.wokeAt).not.toBeNull()
  })
  it('keeps concurrent pending replies durable while one changes admission state', () => {
    const row = make()
    const first = delegationRepo.appendReply(USER, row.id, 'First')
    const second = delegationRepo.appendReply(USER, row.id, 'Second')
    delegationRepo.changeReply(USER, row.id, first.id, 'sending')
    expect(delegationRepo.getById(USER, row.id)?.pendingReplies).toEqual([{ ...first, state: 'sending' }, second])
    delegationRepo.changeReply(USER, row.id, first.id, 'remove')
    expect(delegationRepo.getById(USER, row.id)?.pendingReplies).toEqual([second])
    migrateDelegations(holder.current!.sqlite)
    expect(delegationRepo.getById(USER, row.id)?.pendingReplies).toEqual([second])
  })
  it('backfills legacy handovers idempotently and preserves profile, wake and result state', () => {
    const file = handoverRepo.insert({ userId: USER, agentId: 'bare', folderPath: '/repo', handoverId: '20260919-work', taskId: null, depth: 2, execution: 'ask', state: 'done', briefDigest: 'brief', reportDigest: 'result', reportStatus: 'done', summary: 'Finished', originChatId: 'chat', originAgentId: 'source' })
    handoverRepo.update(USER, file.id, { wokeAt: new Date(1_800_000_000_000), wakeRunId: 'wake' })
    holder.current!.raw.prepare('DELETE FROM delegations').run()
    migrateDelegations(holder.current!.sqlite)
    migrateDelegations(holder.current!.sqlite)
    expect(delegationRepo.list(USER)).toHaveLength(1)
    const row = delegationRepo.getById(USER, file.id)!
    expect(row).toMatchObject({ handoverId: file.id, depth: 2, summary: 'Finished', resultStatus: 'done', wakeRunId: 'wake', wakeDigest: 'result' })
    expect(row.wokeAt?.getTime()).toBe(1_800_000_000_000)
    expect(row.originKey).toBe(delegationOriginKey(row))
  })
  it('backfills a handover that settled unwoken as delivered, and leaves an open one owed', () => {
    const settled = handoverRepo.insert({ userId: USER, agentId: 'bare', folderPath: '/repo', handoverId: '20260901-old', taskId: null, depth: 1, execution: 'ask', state: 'skipped', briefDigest: 'brief', originChatId: 'chat', originAgentId: 'source' })
    const open = handoverRepo.insert({ userId: USER, agentId: 'bare', folderPath: '/repo', handoverId: '20260919-open', taskId: null, depth: 1, execution: 'ask', state: 'blocked', briefDigest: 'brief', reportDigest: 'question', reportStatus: 'blocked', originChatId: 'chat', originAgentId: 'source' })
    holder.current!.raw.prepare('DELETE FROM delegations').run()
    migrateDelegations(holder.current!.sqlite)
    expect(delegationRepo.getById(USER, settled.id)?.wokeAt).not.toBeNull()
    expect(delegationRepo.getById(USER, open.id)?.wokeAt).toBeNull()
  })
})
