import { test, expect } from '../fixtures/app'
import { fakeRemoteAcp } from '../../src/main/agents/drivers/acp/testSupport/fakeRemoteAcp'

test('adds a remote ACP connector, tests its token, streams, answers permission, and continues its session', async ({ cinna }, testInfo) => {
  const peer = await fakeRemoteAcp({ token: 'acp_e2e_fixture', permission: true })
  try {
    await cinna.skipOnboarding()
    await cinna.page.evaluate(() => window.api.settings.set('autoChatTitles', false))
    await cinna.page.getByRole('button', { name: 'Agents', exact: true }).click()
    await cinna.page.getByRole('button', { name: 'Add an agent', exact: true }).click()
    await cinna.page.getByRole('button', { name: /^Remote ACP agent/ }).click()
    const form = cinna.page.getByRole('dialog', { name: 'Add remote ACP agent', exact: true })
    await expect(form.getByLabel('Remote working directory', { exact: true })).toHaveValue('/app/workspace')
    await form.getByLabel('ACP endpoint', { exact: true }).fill(peer.url)
    await form.getByLabel('Access token', { exact: true }).fill('wrong-token')
    await form.getByRole('button', { name: 'Test', exact: true }).click()
    await expect(form.getByRole('alert')).toContainText('access token')
    await expect(form.getByRole('button', { name: 'Add agent', exact: true })).toBeDisabled()
    await form.getByLabel('Access token', { exact: true }).fill('acp_e2e_fixture')
    await form.getByRole('button', { name: 'Test', exact: true }).click()
    await expect(form.getByText('Initialization succeeded: cinna-core · 1.0.0', { exact: true })).toBeVisible()
    expect(peer.received('session/new')).toHaveLength(0)
    await cinna.page.screenshot({ path: testInfo.outputPath('remote-acp-form.png') })
    // Any configuration edit invalidates the successful test receipt in the UI.
    await form.getByLabel('Remote working directory', { exact: true }).fill('/other')
    await expect(form.getByRole('button', { name: 'Add agent', exact: true })).toBeDisabled()
    await form.getByLabel('Remote working directory', { exact: true }).fill('/app/workspace')
    await form.getByRole('button', { name: 'Add agent', exact: true }).click()
    await expect(form).toHaveCount(0)
    const agent = await cinna.page.evaluate(async () => (await window.api.agents.list()).find((row) => row.acpTransport === 'websocket'))
    expect(agent).toMatchObject({ name: 'cinna-core', driver: 'acp', hasAccessToken: true, capabilities: { cwd: false, attachments: 'none', auth: 'token' } })
    expect(JSON.stringify(agent)).not.toContain('acp_e2e_fixture')
    const config = await cinna.page.evaluate((id) => window.api.customAgents.configuration(id), agent!.id)
    expect(config).toMatchObject({ config: { transport: 'websocket', cwd: '/app/workspace' }, hasAccessToken: true })
    expect(JSON.stringify(config)).not.toContain('acp_e2e_fixture')
    const input = cinna.page.getByRole('combobox', { name: 'Type a message...', exact: true })
    await input.fill('Hello from desktop'); await input.press('Enter')
    await expect(cinna.page.getByRole('button', { name: 'Allow once', exact: true })).toBeEnabled()
    await cinna.page.getByRole('button', { name: 'Allow once', exact: true }).click()
    await expect(cinna.page.getByText('Remote answer.', { exact: true })).toBeVisible()
    await expect(cinna.page.getByRole('button', { name: 'Stop', exact: true })).toHaveCount(0)
    await cinna.page.screenshot({ path: testInfo.outputPath('remote-acp-chat.png') })
    await input.fill('Continue the same session'); await input.press('Enter')
    await expect(cinna.page.getByRole('button', { name: 'Allow once', exact: true })).toBeEnabled()
    await cinna.page.getByRole('button', { name: 'Allow once', exact: true }).click()
    await expect(cinna.page.getByRole('button', { name: 'Stop', exact: true })).toHaveCount(0)
    expect(peer.received('session/new')).toHaveLength(1)
    expect(peer.received('session/prompt')).toHaveLength(2)
    expect(peer.received('session/prompt')[0].params?.sessionId).toBe(peer.received('session/prompt')[1].params?.sessionId)
    expect(peer.received('session/new')[0].params).toEqual({ cwd: '/app/workspace', mcpServers: [] })
    expect(peer.headers.every((value) => value.url === '/acp/fixture-connector')).toBe(true)
  } finally { await peer.close() }
})
